### PR TITLE
bug: fix event ingestion and remove bulk import functionality

### PR DESCRIPTION
**Pull request by paigen11**
# Problem Context

A user ran into a problem when attempting to import events in the Sparrow Reference Web App [Routing data from NoteHub to Sparrow reference web app](https://discuss.blues.io/t/routing-data-from-notehub-to-sparrow-reference-web-app/1310).

I was able to recreate the issue locally. The main problem is that the app’s bulk import process and routed event ingestion handler were never updated to handle the updated event structure from Notehub, and newer events fail to parse with a “device uid is not defined” error.

Recommended fix is remove bulk import and update the event ingestion method. We can update the documentation to discuss Notehub’s re-routing ability [Notehub Walkthrough - Blues Developers](https://dev.blues.io/notehub/notehub-walkthrough/#manually-routing-events) instead of bulk import.

## Changes

* Updated the shape of routed Notehub events to reflect the new structure, and fix the code that was throwing errors and preventing the data from being stored in the Postgres DB
* Remove all traces of bulk import functionality - it's no longer needed now that Notehub offers event re-routing
* Update docs and a few error messages to make users aware of Notehub re-routing functionality for their events

## Screenshot (if applicable)

Screenshot 2023-04-05 at 9 46 57 AM

## Testing

Unit / integration / e2e tests?

 All tests pass, code compiles.

Steps to test manually?

1. Set up Postgres DB, set up localtunnel or ngrok connection to ingest events from Notehub route, start DB and app running
2. Route event from Notehub to app manually
3. See event get successfully handled by app, and event data show up on screen in appropriate node or gateway.

Any other sorts of testing notes to include?

## Any other related PRs

n/a

## Ticket(s)

https://trello.com/c/MaIZSt9d/82-sparrow-reference-web-app-bulk-import-event-processing-fails

### CODE REVIEW

**Review by tjvantoll — APPROVED** [review]
Looks great! Thanks for tackling this. fyi it looks like the CI action for this PR seems to be stuck?

**Comment by paigen11** [comment]
> Looks great! Thanks for tackling this. fyi it looks like the CI action for this PR seems to be stuck?

Yeah, I saw that too. @CarltonHenderson - do you have any ideas as to how to get this `build-and-test` workflow to run? I tried re-running it, but it just seems to hang

**Comment by CarltonHenderson** [comment]
I'll check it out right after lunch.

**Comment by CarltonHenderson** [comment]
Fixed in #122 which you can merge into this branch at your convenience.

**Comment by paigen11** [comment]
> Details

Thanks @CarltonHenderson - much appreciated!

**Pull request merged**
